FROM node:18.16
WORKDIR /next/

COPY ./src/package.json ./
RUN npm install && \
    npm install cookie date-fns micro micro-cors && \
    npm install react-redux redux redux-devtools-extension redux-thunk stripe && \
    npm install react-router-dom jwt-decode && \
    npm install chart.js react-chartjs-2 chartjs-plugin-dragdata

WORKDIR /next/src/

# USER node